/**
 * GENERATED by `xanosdk routes --emit`. Do not edit.
 *
 * Plain data plus one interpolator, and the request input types of every
 * endpoint, channel and message. The core sections import nothing; the only
 * imports are the packages an installed module's block declares, never the
 * SDK itself. So a frontend gets the typed path/verb (and socket) contract
 * without pulling the SDK runtime into its bundle. Regenerate after changing an
 * endpoint's name, verb, api group or inputs, or a realtime server's, channel's
 * or message's name or inputs.
 */

/**
 * An own key only. Every lookup here is keyed by a caller's string, and a plain
 * object answers `toString`, `constructor` or `hasOwnProperty` from its
 * prototype — a name no route, channel or param carries would read as one.
 */
function own<T>(record: Record<string, T>, key: string): T | undefined {
  return Object.prototype.hasOwnProperty.call(record, key) ? record[key] : undefined;
}

function fillParams(
  label: string,
  noun: string,
  template: string,
  params?: Record<string, string | number>,
  encode = false,
): string {
  const declared = [...template.matchAll(/\{([^/{}]+)\}/g)].map((m) => m[1]!);
  for (const key of Object.keys(params ?? {})) {
    if (!declared.includes(key)) {
      throw new Error(
        `${label}: \`${key}\` is not a {param} of this ${noun}.` +
          (declared.length ? ` Expected: ${declared.join(", ")}.` : ` This ${noun} is static.`),
      );
    }
  }
  const raw: Record<string, string> = {};
  const filled = template.replace(/\{([^/{}]+)\}/g, (_all, key: string) => {
    const value = own(params ?? {}, key);
    if (value === undefined || value === null || value === "") {
      throw new Error(`${label}: missing a value for the path param \`${key}\`.`);
    }
    if (typeof value === "number" && !Number.isFinite(value)) {
      throw new Error(`${label}: the path param \`${key}\` is ${value}.`);
    }
    const text = String(value);
    if (text.includes("/")) {
      throw new Error(
        `${label}: the path param \`${key}\` cannot contain "/" — ` +
          `it would address a different ${noun}.`,
      );
    }
    if (!encode) {
      if (!/^[A-Za-z0-9_-]+$/.test(text)) {
        throw new Error(
          `${label}: the path param \`${key}\` is "${text}" — a ${noun} segment holds only ` +
            `letters, digits, "_" and "-".`,
        );
      }
      return text;
    }
    raw[key] = encodeURIComponent(text);
    return raw[key];
  });
  // A "." or ".." SEGMENT is REMOVED before routing (and takes the segment
  // before it), and the URL standard reads "%2e" as a dot for that check too.
  // Judged on the segment as sent, values encoded.
  if (encode) {
    for (const segment of template.split("/")) {
      if (!segment.includes("{")) continue;
      const assembled = segment.replace(/\{([^/{}]+)\}/g, (_all, key: string) => raw[key] ?? "");
      if (/^(\.|%2e){1,2}$/i.test(assembled)) {
        throw new Error(
          `${label}: the path segment "${segment}" cannot be "${assembled}" — ` +
            `a "." or ".." segment addresses a different ${noun}.`,
        );
      }
    }
  }
  return filled;
}

export const ROUTES = {
  "GET items": { verb: "GET", path: "/api:tools/items" },
} as const;

/**
 * Every endpoint in this workspace, keyed `"<VERB> <name>"` (e.g. `"GET listings"`),
 * or `"<group>:<VERB> <name>"` when that pair is in more than one api group.
 */
export type RouteName = keyof typeof ROUTES;

export function routePath(name: "GET items"): string;

export function routePath(name: RouteName, params?: Record<string, string | number>): string {
  // Read through a widened view: a workspace with no endpoints at all makes
  // `RouteName` `never`, which cannot index the literal type.
  const route = own(ROUTES as Record<string, { verb: string; path: string }>, name);
  if (!route) {
    throw new Error(
      `routePath: unknown route "${String(name)}". Routes are keyed "<VERB> <name>", ` +
        'e.g. "GET listings" — regenerate the manifest if the endpoint is new.',
    );
  }
  return fillParams(`routePath("${String(name)}")`, "route", route.path, params, true);
}

/**
 * The request body/query inputs of every endpoint, keyed exactly like ROUTES.
 * Path params are inputs too, so they appear here as well as in routePath().
 * Matches InferInput<typeof def>, except that a database-link input appears as
 * the linked table's columns, which is what the server accepts.
 */
export type RouteInputs = {
  "GET items": {
    category?: string;
    status?: "available" | "on_loan" | "in_repair" | "retired";
  };
};

/** The path params of every realtime channel, keyed exactly like CHANNELS. */
export type ChannelInputs = {};

/**
 * The payload of every realtime message, keyed "<channel key> <message name>"
 * (e.g. "rooms/{room_id} send").
 */
export type MessageInputs = {};

/** Every realtime message in this workspace, keyed "<channel key> <message name>". */
export type MessageName = keyof MessageInputs;
